### ISSUE TITLE
tns trying to reinstall git plugin on every livesync reload

### ISSUE THREAD

**Issue by developper89** [mobilemindtec/nativescript-facebook#1]
is this plugin available as a npm nativescript plugin ? 
first i tried to install it with : `tns plugin add nativescript-facebook`
but tns couldn't find the plugin in the npm registry , got : `Registry returned 404 for GET on https://registry.npmjs.org/nativescript-facebook`
than i tried to install it using the git repo `tns plugin add https://github.com/mobilemindtec/nativescript-facebook.git`
second worked but as soon as i save to refresh my code, nativescript is trying to download the plugin again.
I think this would be fixed if you register the plugin as an npm module

**Comment by mobilemindtech** [comment]
Hi,

This plugin not is available as npm. To use, add as dependencie in package.json 

```
"dependencies": {
     "nativescript-facebook": "https://github.com/mobilemindtec/nativescript-facebook.git"
}
```

and run npm update.

**Comment by developper89** [comment]
absolutely , but when i save any file with livesync the app is not updated properly i get:
`npm ERR! install trying to install 0.0.1 to .../node_modules/nativescript-facebook
npm ERR! install but already installed versions [ '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1' ]
nativescript-facebook@0.0.1 node_modules/nativescript-facebook
Project successfully prepared (ios)
Transferring project files...
npm ERR! install trying to install 0.0.1 to .../node_modules/nativescript-facebook
npm ERR! install but already installed versions [ '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1',
npm ERR! install   '0.0.1' ]`

**Comment by developper89** [comment]
problem solved with commit version on git dependency 
`"dependencies": {
     "nativescript-facebook": "https://github.com/mobilemindtec/nativescript-facebook.git#50b147bd5c4cff9f15f879d7bbe20514d591c032",
}`

thank you
