### ISSUE TITLE
plugin break with new nativescript update

### ISSUE THREAD

**Issue by developper89** [mobilemindtec/nativescript-facebook#4]
I can't build my android project anymore , it throws an error saying:
`> Could not find com.android.support:support-annotations:25.3.0`

I think it is because of your android platform code 
`dependencies {
  compile "com.android.support:recyclerview-v7:25.0.1"
  compile("com.facebook.android:facebook-android-sdk:4+", {
    exclude group: 'com.android.support', module: 'support-annotations'
  })
}`

**Comment by mobilemindtech** [comment]
Hi @developper89,

I not believe the problem is this. Have you updated the version of nativescript or this plugin? Verify in your build.gradle the version of this dependency and if the dependency does not exist add with a valid version.
